# -*- coding: utf-8 -*-
"""aula-27/09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1he1FATOtc3dzJwxoSDWB_UT-YU2G3M7S
"""

def mensagem(nome):
  return f

def qtd_vogais(palavra):
  vogais = 'aeiouAEIOU'
  soma = 0
  for letra in palavra:
    if letra in vogais:
      soma += 1
  return soma

print(qtd_vogais('urubu'))

def boas_vindas (nome):
    if nome == 'Adamastor':
        return('Boas Vindas')

print (boas_vindas ('adamastor'))
print (boas_vindas ('mariazinha'))

def calcula_IMC (peso, altura):
    imc = peso / altura ** 2
    return imc


print (calcula_IMC(107, 1.75))

def eh_par(num):
    if num % 2 == 0:
        return True
    else:
        return False

        print (eh_par(2))
        print (eh_par(9))

def soma_elementos(lista):
    soma = 0
    for numero in lista:
        soma += numero
    return soma

print(soma([1, 2, 3, 4]))

def soma_impares(lista):
    soma = 0
    for numero in lista:
        if numero % 2 != 0:
            soma += numero
    return soma

print(soma_impares([1, 2, 3, 4, 5]))
print(soma_impares([10, 11, 12]))

def qtd_vogais(palavra):

 vogais = ['a','e','i','o','u']
    if palavra.lower() in vogais:
        return True
        vogais.count('a','e','i','o','u')
    else:
        return False

  print(soma_vogais('urubu'))
  print(soma_vogais('Mosca'))