# -*- coding: utf-8 -*-
"""aula 27/09 import_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRg5rwOq_XF2FlvGRATMppfY5_pa6c7R
"""

import pandas as pd #pd seria o nome como seria chamado o ''import''

# se o arquivo estiver no seu computador, vc pode fazer upload diretamente
from google.colab import files
uploaded = files.upload()

# df é dataframe
df = pd.read_csv('clubes-futebol.csv')

df.head()

estadios = df['Estadio'].tolist()
print(estadios)

Gols_Visitante = df['Gols_Visitante'].tolist()
print(Gols_Visitante)

df_casa_gols = df[['Time_Casa','Gols_Casa']]

display(df_casa_gols)

